# escape=`
FROM microsoft/iis
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

RUN `
    # Disable DNS cache.
    Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name ServerPriorityTimeLimit -Value 0 -Type DWord; `
    # Install ASP.NET.
    Install-WindowsFeature NET-Framework-45-ASPNET; `
    Install-WindowsFeature Web-Asp-Net45; `
    # Install Chocolatey.
    $env:chocolateyUseWindowsCompression = 'false'; `
    iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex; `
    # Install WebDeploy, Psake.
    choco install webdeploy psake -y

COPY scripts C:\Temp\scripts
COPY default.ps1 C:\Temp\default.ps1

COPY ZergRushCo.zip Temp\ZergRushCo.zip

WORKDIR C:\Temp
RUN ["psake.bat", "publish-zergrushco", "-properties", "@{ServerHost='localhost';SiteName='Default Web Site'}"]

EXPOSE 80
