# escape=`
FROM microsoft/mssql-server-windows-express:2017-CU1
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

ENV `
    # SQL Server variables.
    sa_password=29hHzGtB `
    ACCEPT_EULA=Y

COPY CreateDB.sql C:\Temp\CreateDB.sql

# Wait for SQL Server to start.
RUN for ($i = 1; $i -le 10; $i++) { $result = Test-NetConnection localhost -Port 1433; if ($result.TcpTestSucceeded) { break }; Start-Sleep 1 }

RUN sqlcmd -i C:\Temp\CreateDB.sql
