//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saritasa.Tools.Domain.Localization.System.ComponentModel.Annotations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saritasa.Tools.Domain.Localization.System.ComponentModel.Annotations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field does not equal any of the values specified in AllowedValuesAttribute..
        /// </summary>
        public static string AllowedValuesAttribute_Invalid {
            get {
                return ResourceManager.GetString("AllowedValuesAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid Base64 encoding..
        /// </summary>
        public static string Base64StringAttribute_Invalid {
            get {
                return ResourceManager.GetString("Base64StringAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; and &apos;{1}&apos; do not match..
        /// </summary>
        public static string CompareAttribute_MustMatch {
            get {
                return ResourceManager.GetString("CompareAttribute_MustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid credit card number..
        /// </summary>
        public static string CreditCardAttribute_Invalid {
            get {
                return ResourceManager.GetString("CreditCardAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid..
        /// </summary>
        public static string CustomValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field equals one of the values specified in DeniedValuesAttribute..
        /// </summary>
        public static string DeniedValuesAttribute_Invalid {
            get {
                return ResourceManager.GetString("DeniedValuesAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid e-mail address..
        /// </summary>
        public static string EmailAddressAttribute_Invalid {
            get {
                return ResourceManager.GetString("EmailAddressAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field only accepts files with the following extensions: {1}.
        /// </summary>
        public static string FileExtensionsAttribute_Invalid {
            get {
                return ResourceManager.GetString("FileExtensionsAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string or collection type with a minimum length of &apos;{1}&apos; and maximum length of &apos;{2}&apos;..
        /// </summary>
        public static string LengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("LengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string or array type with a maximum length of &apos;{1}&apos;..
        /// </summary>
        public static string MaxLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string or array type with a minimum length of &apos;{1}&apos;..
        /// </summary>
        public static string MinLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MinLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid phone number..
        /// </summary>
        public static string PhoneAttribute_Invalid {
            get {
                return ResourceManager.GetString("PhoneAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between {1} and {2}..
        /// </summary>
        public static string RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between {1} and {2} exclusive..
        /// </summary>
        public static string RangeAttribute_ValidationError_MaxExclusive {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError_MaxExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between {1} exclusive and {2}..
        /// </summary>
        public static string RangeAttribute_ValidationError_MinExclusive {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError_MinExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between {1} exclusive and {2} exclusive..
        /// </summary>
        public static string RangeAttribute_ValidationError_MinExclusive_MaxExclusive {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError_MinExclusive_MaxExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a maximum length of {1}..
        /// </summary>
        public static string StringLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a minimum length of {2} and a maximum length of {1}..
        /// </summary>
        public static string StringLengthAttribute_ValidationErrorIncludingMinimum {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationErrorIncludingMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid fully-qualified http, https, or ftp URL..
        /// </summary>
        public static string UrlAttribute_Invalid {
            get {
                return ResourceManager.GetString("UrlAttribute_Invalid", resourceCulture);
            }
        }
    }
}
