//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saritasa.Tools.Messages.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Strings() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saritasa.Tools.Messages.Properties.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} must be greater than {1}..
        /// </summary>
        public static string ArgumentMustBeGreaterThan {
            get {
                return ResourceManager.GetString("ArgumentMustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} must be less than {1}..
        /// </summary>
        public static string ArgumentMustBeLessThan {
            get {
                return ResourceManager.GetString("ArgumentMustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Assemblies to search handlers were not specified..
        /// </summary>
        public static string AssembliesNotSpecified {
            get {
                return ResourceManager.GetString("AssembliesNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot create delegate..
        /// </summary>
        public static string CannotCreateDelegate {
            get {
                return ResourceManager.GetString("CannotCreateDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot evaluate type {0}..
        /// </summary>
        public static string CannotEvaluateExpression {
            get {
                return ResourceManager.GetString("CannotEvaluateExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot find method {0}..
        /// </summary>
        public static string CannotFindMethod {
            get {
                return ResourceManager.GetString("CannotFindMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot load type {0}..
        /// </summary>
        public static string CannotLoadType {
            get {
                return ResourceManager.GetString("CannotLoadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot resolve handler {0}..
        /// </summary>
        public static string CannotResolveHandler {
            get {
                return ResourceManager.GetString("CannotResolveHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Query object of type {0} cannot be resolved..
        /// </summary>
        public static string CannotResolveQueryObject {
            get {
                return ResourceManager.GetString("CannotResolveQueryObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot use comparison operator {0}..
        /// </summary>
        public static string CannotUseComparisonOperator {
            get {
                return ResourceManager.GetString("CannotUseComparisonOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot use comparison operator {0} for NULL values..
        /// </summary>
        public static string CannotUseComparisonOperatorNull {
            get {
                return ResourceManager.GetString("CannotUseComparisonOperatorNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Found handler {0} for command {1}..
        /// </summary>
        public static string CommandHandlerFound {
            get {
                return ResourceManager.GetString("CommandHandlerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot find command handler {0} or it cannot be resolved. Make sure it has default public parameterless constructor or registered with your dependency injection container..
        /// </summary>
        public static string CommandHandlerNotFound {
            get {
                return ResourceManager.GetString("CommandHandlerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Content should be {0} type..
        /// </summary>
        public static string ContentShouldBeType {
            get {
                return ResourceManager.GetString("ContentShouldBeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Found handler {0} for event {1}..
        /// </summary>
        public static string EventHandlerFound {
            get {
                return ResourceManager.GetString("EventHandlerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No handlers found for event {0}..
        /// </summary>
        public static string EventHandlerNotFound {
            get {
                return ResourceManager.GetString("EventHandlerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Exception while resolving {0}: {1}..
        /// </summary>
        public static string ExceptionOnResolve {
            get {
                return ResourceManager.GetString("ExceptionOnResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} occurred while process {1}: {2}..
        /// </summary>
        public static string ExceptionWhileProcess {
            get {
                return ResourceManager.GetString("ExceptionWhileProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expression must have Body of type MethodCallExpression..
        /// </summary>
        public static string ExpressionMethodCallExpressionBody {
            get {
                return ResourceManager.GetString("ExpressionMethodCallExpressionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to For some reason InnerException is null. Type {0}..
        /// </summary>
        public static string InnerExceptionIsNull {
            get {
                return ResourceManager.GetString("InnerExceptionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Message should be {0} type..
        /// </summary>
        public static string MessageShouldBeType {
            get {
                return ResourceManager.GetString("MessageShouldBeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Method does not declare type..
        /// </summary>
        public static string MethodNoTypeDeclare {
            get {
                return ResourceManager.GetString("MethodNoTypeDeclare", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to There are middlewares with duplicated identifiers {0}..
        /// </summary>
        public static string MiddlewareDuplicate {
            get {
                return ResourceManager.GetString("MiddlewareDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Middleware with identifier {0} already exists..
        /// </summary>
        public static string MiddlewareExists {
            get {
                return ResourceManager.GetString("MiddlewareExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Middleware not found..
        /// </summary>
        public static string MiddlewareNotFound {
            get {
                return ResourceManager.GetString("MiddlewareNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot find command handlers in assemblie(-s) {0}..
        /// </summary>
        public static string NoHandlersInAssembly {
            get {
                return ResourceManager.GetString("NoHandlersInAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot specify method name and type from content type..
        /// </summary>
        public static string NoMethodNameFromContentType {
            get {
                return ResourceManager.GetString("NoMethodNameFromContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Looking for command handler for command {0}..
        /// </summary>
        public static string SearchCommandHandler {
            get {
                return ResourceManager.GetString("SearchCommandHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot find command handler for command {0} in assemblies {1}..
        /// </summary>
        public static string SearchCommandHandlerNotFound {
            get {
                return ResourceManager.GetString("SearchCommandHandlerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Looking for event handler for event {0}..
        /// </summary>
        public static string SearchEventHandler {
            get {
                return ResourceManager.GetString("SearchEventHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot find event handler for event {0} in assemblies {1}..
        /// </summary>
        public static string SearchEventHandlerNotFound {
            get {
                return ResourceManager.GetString("SearchEventHandlerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Serializer should be text-based..
        /// </summary>
        public static string SerializerShouldBeText {
            get {
                return ResourceManager.GetString("SerializerShouldBeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error while executing message: {0}..
        /// </summary>
        public static string WebEndpoint_ErrorExecuteMessage {
            get {
                return ResourceManager.GetString("WebEndpoint_ErrorExecuteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Incorrect request..
        /// </summary>
        public static string WebEndpoint_IncorrectRequest {
            get {
                return ResourceManager.GetString("WebEndpoint_IncorrectRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pipeline not found for message type {0}, id: {1}, content type: {2}..
        /// </summary>
        public static string WebEndpoint_PipelineNotFound {
            get {
                return ResourceManager.GetString("WebEndpoint_PipelineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Processing message id: {0} content type: {1}..
        /// </summary>
        public static string WebEndpoint_ProcessingMessage {
            get {
                return ResourceManager.GetString("WebEndpoint_ProcessingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Incoming request from {0} {1}..
        /// </summary>
        public static string WebEndpoint_Request {
            get {
                return ResourceManager.GetString("WebEndpoint_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Web endpoint started on {0}:{1}..
        /// </summary>
        public static string WebEndpoint_StartedOn {
            get {
                return ResourceManager.GetString("WebEndpoint_StartedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Web endpoint starting on {0}:{1}..
        /// </summary>
        public static string WebEndpoint_StartingOn {
            get {
                return ResourceManager.GetString("WebEndpoint_StartingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Web endpoint stop requested..
        /// </summary>
        public static string WebEndpoint_Stop {
            get {
                return ResourceManager.GetString("WebEndpoint_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Web endpoint stopped..
        /// </summary>
        public static string WebEndpoint_Stopped {
            get {
                return ResourceManager.GetString("WebEndpoint_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value cannot be an empty collection..
        /// </summary>
        public static string WebEndpoint_ValueCannotBeEmptyColleciton {
            get {
                return ResourceManager.GetString("WebEndpoint_ValueCannotBeEmptyColleciton", resourceCulture);
            }
        }
    }
}
