//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saritasa.Tools.Common.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Strings() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saritasa.Tools.Common.Properties.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} cannot be empty guid..
        /// </summary>
        public static string ArgumentCannotBeEmptyGuid {
            get {
                return ResourceManager.GetString("ArgumentCannotBeEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} cannot be empty string..
        /// </summary>
        public static string ArgumentCannotBeEmptyString {
            get {
                return ResourceManager.GetString("ArgumentCannotBeEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} cannot be more than {1} character..
        /// </summary>
        public static string ArgumentCannotBeMoreThanChars {
            get {
                return ResourceManager.GetString("ArgumentCannotBeMoreThanChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} period cannot be used..
        /// </summary>
        public static string ArgumentCannotBeThePeriod {
            get {
                return ResourceManager.GetString("ArgumentCannotBeThePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} must be between {1}-{2}..
        /// </summary>
        public static string ArgumentMustBeBetween {
            get {
                return ResourceManager.GetString("ArgumentMustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Argument must be enum..
        /// </summary>
        public static string ArgumentMustBeEnum {
            get {
                return ResourceManager.GetString("ArgumentMustBeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} must be greater than {1}..
        /// </summary>
        public static string ArgumentMustBeGreaterThan {
            get {
                return ResourceManager.GetString("ArgumentMustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} must be less than {1}..
        /// </summary>
        public static string ArgumentMustBeLessThan {
            get {
                return ResourceManager.GetString("ArgumentMustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} is not a valid email address..
        /// </summary>
        public static string ArgumentNotValidEmail {
            get {
                return ResourceManager.GetString("ArgumentNotValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Collection cannot be empty..
        /// </summary>
        public static string CollectionCannotEmpty {
            get {
                return ResourceManager.GetString("CollectionCannotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} contains method that is not possible to recognize..
        /// </summary>
        public static string HashMethodCannotRecognize {
            get {
                return ResourceManager.GetString("HashMethodCannotRecognize", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} does not contain hash method..
        /// </summary>
        public static string NoHashMethod {
            get {
                return ResourceManager.GetString("NoHashMethod", resourceCulture);
            }
        }
    }
}
