//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

namespace Saritasa.Tools.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saritasa.Tools.Common.Properties.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty guid..
        /// </summary>
        internal static string ArgumentCannotBeEmptyGuid {
            get {
                return ResourceManager.GetString("ArgumentCannotBeEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty string..
        /// </summary>
        internal static string ArgumentCannotBeEmptyString {
            get {
                return ResourceManager.GetString("ArgumentCannotBeEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be more than {1} character..
        /// </summary>
        internal static string ArgumentCannotBeMoreThanChars {
            get {
                return ResourceManager.GetString("ArgumentCannotBeMoreThanChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} period cannot be used..
        /// </summary>
        internal static string ArgumentCannotBeThePeriod {
            get {
                return ResourceManager.GetString("ArgumentCannotBeThePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time kinds must be equal..
        /// </summary>
        internal static string ArgumentDateTimeKindMustBeEqual {
            get {
                return ResourceManager.GetString("ArgumentDateTimeKindMustBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1}-{2}..
        /// </summary>
        internal static string ArgumentMustBeBetween {
            get {
                return ResourceManager.GetString("ArgumentMustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}..
        /// </summary>
        internal static string ArgumentMustBeGreaterThan {
            get {
                return ResourceManager.GetString("ArgumentMustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}..
        /// </summary>
        internal static string ArgumentMustBeLessThan {
            get {
                return ResourceManager.GetString("ArgumentMustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid email address..
        /// </summary>
        internal static string ArgumentNotValidEmail {
            get {
                return ResourceManager.GetString("ArgumentNotValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection cannot be empty..
        /// </summary>
        internal static string CollectionCannotEmpty {
            get {
                return ResourceManager.GetString("CollectionCannotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains method that is not possible to recognize..
        /// </summary>
        internal static string HashMethodCannotRecognize {
            get {
                return ResourceManager.GetString("HashMethodCannotRecognize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot recognize sort direction {0}..
        /// </summary>
        internal static string InvalidOrderDirection {
            get {
                return ResourceManager.GetString("InvalidOrderDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not contain hash method..
        /// </summary>
        internal static string NoHashMethod {
            get {
                return ResourceManager.GetString("NoHashMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordering by field {0} is not supported..
        /// </summary>
        internal static string OrderByFieldIsNotSupported {
            get {
                return ResourceManager.GetString("OrderByFieldIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect target string length..
        /// </summary>
        internal static string TargetStringLengthIncorrect {
            get {
                return ResourceManager.GetString("TargetStringLengthIncorrect", resourceCulture);
            }
        }
    }
}
