# escape=`
FROM microsoft/mssql-server-windows-express
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

ENV `
    # SQL Server variables.
    sa_password=29hHzGtB `
    ACCEPT_EULA=Y

COPY CreateDB.sql C:\Temp\CreateDB.sql

# TODO: Wait for SQL Server start here.

RUN sqlcmd -i C:\Temp\CreateDB.sql
