# escape=`
FROM microsoft/aspnet
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

RUN `
    # Disable DNS cache.
    Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name ServerPriorityTimeLimit -Value 0 -Type DWord; `
    # Install Chocolatey.
    $env:chocolateyUseWindowsCompression = 'false'; `
    iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex; `
    # Install WebDeploy, Psake.
    choco install webdeploy psake -y

COPY docs C:\Temp\docs
COPY scripts C:\Temp\scripts
COPY default.ps1 C:\Temp\default.ps1

ENV DockerDir samples\Saritasa.BoringWarehouse\Docker

COPY ${DockerDir}\BoringWarehouse.zip C:\Temp\BoringWarehouse.zip

WORKDIR C:\Temp
RUN psake publish-boringwarehouse

EXPOSE 80
